name: Build Executables

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'gui.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'amender-${{ matrix.os }}-${{ github.run_number }}-${{ github.run_attempt }}.exe'
          options: --onefile, --windowed
